# Generated by Django 5.0.3 on 2024-03-18 05:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('author', models.CharField(null=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=None)),
                ('image_url', models.CharField(null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=None)),
                ('description', models.TextField()),
                ('avg_rating', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('have_electronic_version', models.BooleanField()),
                ('have_physical_version', models.BooleanField()),
                ('sources', models.JSONField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
