# Generated by Django 5.0.3 on 2024-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_aggregator', '0002_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_stats',
            field=models.JSONField(default={}),
        ),
    ]
