# Generated by Django 5.0.3 on 2024-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_aggregator', '0002_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
