# Generated by Django 5.0.3 on 2024-03-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_aggregator', '0005_ratingstar_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='disadvantages',
        ),
    ]
